name: dio_http_cache
description: http cache lib for Flutter dio like RxCache. It uses sqflite as disk cache, and google/quiver-dart/LRU strategy as memory cache.
version: 0.3.0
authors:
  - Hurshi <ihsruh@gmail.com>
  - Eric Kok <erickok@gmail.com>
homepage: https://github.com/hurshi/dio-http-cache

environment:
  sdk: '>=2.18.0 <3.0.0'  # Updated for latest Flutter support, check latest Dart SDK

dependencies:
  crypto: ^3.0.5        # Updated to the latest version
  dio: ^5.6.0           # Updated to the latest version compatible with new Flutter
  flutter:
    sdk: flutter
  json_serializable: ^6.8.0  # Updated to the latest version
  json_annotation: ^4.9.0  # Updated to the latest version
  path: ^1.9.0              # Updated to the latest version
  quiver: ^3.2.2            # Check for newer versions if available
  sqflite: ^2.3.3+1          # Updated to the latest version

dev_dependencies:
  build_runner: ^2.4.12      # Updated to the latest version
  flutter_test:
    sdk: flutter

flutter:
  module:
    androidX: true  # AndroidX compatibility is necessary for latest Flutter versions
